"use client";
import { GripVertical, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { SortableDndContainer } from "@/components/common/sortable-dnd-container";
import { LabeledInput } from "@/components/forms/labeled-input";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { JoinCopyFields } from "../../_components/join-copy-fields";
import { JoinSectionEditor } from "../../_components/join-section-editor";
import type { JoinSections } from "@/lib/types/join";
import { createItemId, normaliseOrder } from "@/lib/utils";
export function JoinNextStepsEditor({ initial }: { initial: JoinSections["nextSteps"] }) { return <JoinSectionEditor section="nextSteps" initial={initial} title="What happens next" description="Explain the path after a creator applies.">{({ value, readOnly, onChange }) => <Fields value={value} readOnly={readOnly} onChange={onChange} />}</JoinSectionEditor>; }
function Fields({ value, readOnly, onChange }: { value: JoinSections["nextSteps"]; readOnly: boolean; onChange: (next: JoinSections["nextSteps"]) => void }) { const [remove, setRemove] = useState<string | null>(null); const update = (patch: Partial<JoinSections["nextSteps"]>) => onChange({ ...value, ...patch }); return <div className="space-y-6"><JoinCopyFields idPrefix="join-next" value={value} readOnly={readOnly} onChange={update} /><section className="rounded-md border border-[#c5d4cd] bg-[#f8fbf9] p-4 sm:p-5"><div className="flex items-start justify-between border-b border-[#d7e1dc] pb-4"><div><h3 className="font-bold text-[#163a37]">Steps</h3><p className="mt-1 text-sm text-[#61746d]">Drag cards to define the public order.</p></div><Button disabled={readOnly || value.steps.length >= 8} size="sm" type="button" variant="outline" onClick={() => update({ steps: [...value.steps, { id: createItemId("join-step"), title: "", copy: "", order: value.steps.length }] })}><Plus /> Add step</Button></div><SortableDndContainer className="mt-4 grid gap-3 lg:grid-cols-2" disabled={readOnly} items={value.steps} layout="grid" sortableItems onReorder={(steps) => update({ steps: normaliseOrder(steps) })}>{(step, index) => <article className="rounded-sm border border-[#d7e1dc] bg-white p-4"><div className="mb-3 flex justify-between"><span className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-[#47635b]"><GripVertical className="size-4 cursor-grab" /> Step {index + 1}</span><Button aria-label={`Delete step ${index + 1}`} className="text-[#a55353]" disabled={readOnly || value.steps.length === 1} size="icon-sm" type="button" variant="ghost" onClick={() => setRemove(step.id)}><Trash2 /></Button></div><div className="space-y-4"><LabeledInput id={`join-step-${step.id}`} label="Title" readOnly={readOnly} value={step.title} onChange={(title) => update({ steps: value.steps.map((item) => item.id === step.id ? { ...item, title } : item) })} /><div><label className="text-sm font-medium">Copy</label><Textarea className="mt-2 min-h-24" readOnly={readOnly} value={step.copy} onChange={(event) => update({ steps: value.steps.map((item) => item.id === step.id ? { ...item, copy: event.target.value } : item) })} /></div></div></article>}</SortableDndContainer></section><AlertDialog open={Boolean(remove)} onOpenChange={(open) => !open && setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove step?</AlertDialogTitle><AlertDialogDescription>This only changes the draft until you save.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={() => { if (remove) update({ steps: normaliseOrder(value.steps.filter((step) => step.id !== remove)) }); setRemove(null); }}>Remove</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>; }
