services:
  mongodb:
    image: mongo:8.3-noble
    container_name: mongodb_tumedia
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGO_INITDB_DATABASE: tumedia
    volumes:
      - mongo_data:/data/db
      - mongo_config_data:/data/configdb
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-init:
    image: mongo:8.3-noble
    container_name: mongodb_tumedia_init
    depends_on:
      - mongodb
    restart: "no"
    tmpfs:
      - /data/db
      - /data/configdb
    entrypoint: >
      bash -c "
        echo 'Waiting for MongoDB to start...';

        until mongosh --host mongodb:27017 --quiet --eval 'db.adminCommand(\"ping\").ok'; do
          sleep 2;
        done;

        echo 'MongoDB is up. Checking replica set...';

        mongosh --host mongodb:27017 --quiet --eval '
          try {
            rs.status();
            print(\"Replica set already initialized\");
          } catch (err) {
            print(\"Initializing replica set...\");
            rs.initiate({
              _id: \"rs0\",
              members: [
                {
                  _id: 0,
                  host: \"localhost:27017\"
                }
              ]
            });
          }
        ';

        echo 'Replica set init complete.';
      "

  redis:
    image: redis:7-alpine
    container_name: redis_tumedia
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  mongo_config_data:
  redis_data:
