import Link from "next/link";
import { ChevronLeft, ChevronRight, MoreHorizontal } from "lucide-react";

export function CmsPagination({ pathname, searchParams, page, total, limit, itemName = "items" }: { pathname: string; searchParams: Record<string, string | undefined>; page: number; total: number; limit: number; itemName?: string }) {
  const totalPages = Math.max(1, Math.ceil(total / limit));
  if (totalPages <= 1) return null;
  const pages = totalPages <= 7 ? Array.from({ length: totalPages }, (_, index) => index + 1) : [1, ...(page > 3 ? ["…"] : []), ...Array.from({ length: 3 }, (_, index) => Math.min(totalPages - 1, Math.max(2, page - 1 + index))), ...(page < totalPages - 2 ? ["…"] : []), totalPages];
  const href = (next: number) => { const params = new URLSearchParams(); Object.entries(searchParams).forEach(([key, value]) => { if (value && key !== "page") params.set(key, value); }); if (next > 1) params.set("page", String(next)); const query = params.toString(); return query ? `${pathname}?${query}` : pathname; };
  const start = (page - 1) * limit + 1;
  const end = Math.min(page * limit, total);
  return <nav aria-label={`${itemName} pagination`} className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[#d7e1dc] pt-4"><p className="text-sm text-[#61746d]">Showing {start}–{end} of {total} {itemName}</p><div className="flex items-center gap-1"><Link aria-disabled={page === 1} className={`inline-flex h-7 items-center gap-1 rounded-md border border-slate-300 bg-white px-2.5 text-[0.8rem] font-semibold ${page === 1 ? "pointer-events-none opacity-50" : "hover:bg-slate-50"}`} href={page === 1 ? pathname : href(page - 1)}><ChevronLeft className="size-3.5" /> Previous</Link>{pages.map((item, index) => item === "…" ? <span className="grid size-8 place-items-center text-[#61746d]" key={`${item}-${index}`}><MoreHorizontal className="size-4" /></span> : <Link aria-current={item === page ? "page" : undefined} className={`grid size-8 place-items-center rounded-md border text-sm font-semibold ${item === page ? "border-[#0b0d17] bg-[#0b0d17] text-white" : "border-slate-300 bg-white hover:bg-slate-50"}`} href={href(item as number)} key={item}>{item}</Link>)}<Link aria-disabled={page === totalPages} className={`inline-flex h-7 items-center gap-1 rounded-md border border-slate-300 bg-white px-2.5 text-[0.8rem] font-semibold ${page === totalPages ? "pointer-events-none opacity-50" : "hover:bg-slate-50"}`} href={page === totalPages ? pathname : href(page + 1)}>Next <ChevronRight className="size-3.5" /></Link></div></nav>;
}
