import { CmsEditorPageShell } from "@/components/common/cms-editor-page-shell";
import { CmsPagination } from "@/components/common/cms-pagination";
import { cmsActivityRepository } from "@/lib/db/repositories/cms-activity.repository";

const formatDate = (date: Date) => new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date);

export default async function ActivityLogsPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const query = await searchParams; const requested = Math.max(1, Number(query.page) || 1); const limit = 30;
  const first = await cmsActivityRepository.listPage(requested, limit); const page = Math.min(requested, Math.max(1, Math.ceil(first.total / limit))); const result = page === requested ? first : await cmsActivityRepository.listPage(page, limit);
  return <CmsEditorPageShell eyebrow="Settings" title="Activity logs" description="A paginated audit trail of content, settings, and submission actions performed in the CMS." breadcrumbs={[{ label: "Overview", href: "/" }, { label: "Settings", href: "/settings" }, { label: "Activity logs" }]}><section className="overflow-hidden rounded-xl border border-[#c5d4cd] bg-white"><div className="border-b border-[#d7e1dc] px-5 py-4"><h2 className="font-bold text-[#173c38]">CMS activity</h2><p className="mt-1 text-sm text-[#61746d]">30 actions per page, newest first.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f3f7f5] text-xs font-bold uppercase tracking-[0.08em] text-[#52605d]"><tr><th className="px-5 py-3">Administrator</th><th className="px-5 py-3">Action</th><th className="px-5 py-3">Target</th><th className="px-5 py-3">When</th></tr></thead><tbody className="divide-y divide-[#e1e9e5]">{result.items.length ? result.items.map((entry) => <tr key={entry._id.toString()} className="text-[#314945]"><td className="px-5 py-4 font-semibold">{entry.email}</td><td className="px-5 py-4 capitalize">{entry.action.replaceAll("_", " ")}</td><td className="px-5 py-4 text-[#52605d]">{entry.target}</td><td className="whitespace-nowrap px-5 py-4 text-[#52605d]">{formatDate(entry.createdAt)}</td></tr>) : <tr><td colSpan={4} className="px-5 py-12 text-center text-[#61746d]">No CMS activity has been recorded yet.</td></tr>}</tbody></table></div><div className="px-5 pb-4"><CmsPagination pathname="/settings/activity" searchParams={query} page={page} total={result.total} limit={limit} itemName="activities" /></div></section></CmsEditorPageShell>;
}
