import type { WithId } from "mongodb";
import { BaseRepository } from "@/lib/db/repositories/base.repository";
import type { CreatorSubmission, CreatorSubmissionStatus, JoinContent, JoinSections } from "@/lib/types/join";

function defaults(): JoinContent {
  const now = new Date();
  return { key: "join", createdAt: now, updatedAt: now, seo: { title: "Join the TU Media creator network", description: "Tell TU Media about your work, audience, and the technology stories you want to create." }, hero: { eyebrow: "TU Media creator network", title: "Make technology feel", emphasis: "human.", description: "For creators who turn products into ideas people want to try, share, and talk about. Tell us about your work and the audience you have built around it.", ctaLabel: "Start your application", media: { type: "video", url: "/videos/video-2.mp4", posterUrl: "/images/12.jpeg", alt: "Creators producing technology content" } }, application: { eyebrow: "Creator application", title: "Show us what your audience comes", emphasis: "back for.", description: "This short application helps us understand the kind of work you make, who it reaches, and what collaborations may be relevant. It is an introduction—not a guarantee of a campaign or compensation.", privacyLabel: "How we use your information" }, nextSteps: { eyebrow: "What happens next", title: "A simple way to meet, then see where a good", emphasis: "fit", description: "We keep the process clear from the beginning, so you can make informed decisions about the opportunities that come your way.", steps: [["Share your work", "Tell us about your content, audience, and creative point of view."], ["Meet the right brief", "We introduce relevant opportunities when there is a genuine fit."], ["Choose with clarity", "You can review the details before deciding whether to take part."]].map(([title, copy], order) => ({ id: `join-step-${order + 1}`, title, copy, order })) }, faq: { eyebrow: "Creator FAQ", title: "Good questions make for better", description: "Everything you need to know before introducing yourself to the network.", items: [["Do I need a certain follower count to apply?", "No. We consider content quality, audience trust, format, niche, and fit alongside audience size."], ["Will applying guarantee campaign work?", "No. An application lets us learn about your work. We only contact creators when there is a relevant opportunity or follow-up."], ["Can I apply if I already work with other brands?", "Yes. Any particular campaign terms, including exclusivity where applicable, are discussed before you decide to participate."], ["What should I include in my social links?", "Share the profiles where you publish your strongest or most representative work, including the platform you use most often."]].map(([question, answer], order) => ({ id: `join-faq-${order + 1}`, question, answer, order })) } };
}

export class JoinRepository extends BaseRepository<JoinContent> {
  protected readonly collectionName = "joinContent";
  async get(): Promise<WithId<JoinContent>> { const current = await this.findOne({ key: "join" }); if (!current) return this.insertOne(defaults()); const fallback = defaults(); return { ...fallback, ...current, hero: { ...fallback.hero, ...current.hero }, application: { ...fallback.application, ...current.application }, nextSteps: { ...fallback.nextSteps, ...current.nextSteps }, faq: { ...fallback.faq, ...current.faq } }; }
  async updateSection<TKey extends keyof JoinSections>(section: TKey, data: JoinSections[TKey], updatedBy: string) { return this.updateOne({ key: "join" }, { $set: { [section]: data, updatedAt: new Date(), updatedBy } }); }
}

export class CreatorSubmissionRepository extends BaseRepository<CreatorSubmission> {
  protected readonly collectionName = "creatorSubmissions";
  async create(data: Omit<CreatorSubmission, "status" | "createdAt" | "updatedAt">) { const now = new Date(); return this.insertOne({ ...data, status: "unread", createdAt: now, updatedAt: now }); }
  async list({ page, limit, search, status, sort = "newest" }: { page: number; limit: number; search?: string; status?: CreatorSubmissionStatus; sort?: "newest" | "oldest" }) { const filter: Record<string, unknown> = {}; if (status) filter.status = status; if (search?.trim()) { const expression = { $regex: search.trim(), $options: "i" }; filter.$or = [{ fullName: expression }, { email: expression }, { niche: expression }]; } const collection = this.collection(); const [items, total] = await Promise.all([collection.find(filter).sort({ createdAt: sort === "oldest" ? 1 : -1 }).skip((page - 1) * limit).limit(limit).toArray(), collection.countDocuments(filter)]); return { items, total }; }
  async listAll() { return this.collection().find({}).sort({ createdAt: 1 }).toArray(); }
  async markRead(id: string) { const { ObjectId } = await import("mongodb"); if (!ObjectId.isValid(id)) return null; return this.updateOne({ _id: new ObjectId(id) } as never, { $set: { status: "read", updatedAt: new Date() } }); }
  async deleteMany(ids: string[]) { const { ObjectId } = await import("mongodb"); const objectIds = ids.filter(ObjectId.isValid).map((id) => new ObjectId(id)); if (objectIds.length) await this.collection().deleteMany({ _id: { $in: objectIds } }); }
}
export const joinRepository = new JoinRepository();
export const creatorSubmissionRepository = new CreatorSubmissionRepository();
