import type { LandingContent } from "@/lib/types/landing";
const id = (value: string) => value;
const defaultMarqueeIconKeys = [
  "smartphone",
  "bot",
  "laptop",
  "gamepad",
  "headphones",
  "home",
] as const;
export function landingDefaults(): LandingContent {
  const now = new Date();
  return { key: "landing", createdAt: now, updatedAt: now, seo: { title: "TU Media | Creator marketing for technology brands", description: "TU Media connects technology brands with creators who make products worth discovering." },
    hero: { eyebrow: "Technology × Creator culture", title: "Launch With Confidence,", emphasis: "Grow With Creators", description: "We connect ambitious brands with trusted creators and produce exceptional content that turns launches into long-term growth.", ctas: [{ id: "hero-contact", label: "Connect with us", href: "/contact", variant: "primary", order: 0 }, { id: "hero-work", label: "See our work", href: "/projects", variant: "secondary", order: 1 }], backgroundMedia: { type: "image", url: "/images/hero-bg.webp", alt: "Creators producing technology content for TU Media" }, scrollLabel: "Scroll to discover" },
    positioning: { title: "Growth through influence.", description: "Technology is not sold by listing features. It's sold when people see it solving real problems, improving everyday life, and being recommended by creators they already trust. That's where we come in.", cta: { label: "Meet TU Media", href: "/about" }, stats: [["90%","Partners returning for more"],["10,000+","Creator activations coordinated"],["6+","Years growing technology stories"]].map(([value,label],order) => ({ id: id(`stat-${order}`), value, label, order })), marqueeItems: ["Consumer tech","Smart home & robotics","Software & AI","Gaming & mobility","Creator hardware","Connected living"].map((label,order) => ({ id: id(`marquee-${order}`), label, iconKey: defaultMarqueeIconKeys[order] ?? "smartphone", order })) },
    process: { eyebrow: "How we work", title: "Strategy first. Execution that performs.", description: "Every successful campaign starts with understanding the product, the audience, and the creators who can tell its story. We combine strategy, production, and creator partnerships to launch campaigns that generate real business results.", cta: { label: "Our approach", href: "/services#our-approach" }, media: { url: "/images/1.jpeg", alt: "Person exploring virtual reality technology" }, imageWordmark: "PRODUCT\nMEETS\nPEOPLE", steps: ["Share Your Brief","Match the Right Creators","Launch the Campaign","Measure & Scale"].map((title,order) => ({ id: id(`process-${order}`), title, order })) },
    creatorFlowCta: { eyebrow: "For creators", title: "Your next great brief could start with a better introduction.", description: "Join the TU Media creator network to share the work you are proud of and the audiences you know best. When a relevant opportunity comes up, we will know where to begin.", cta: { label: "Join the creator network", href: "/join" }, media: { url: "/images/creator-flow.png", alt: "Creator working through a content workflow" }, mediaCaption: "A network built around people and their point of view" },
    industriesPreview: { eyebrow: "Industry focus", title: "Built for Brands Driving Innovation", description: "From consumer technology to AI software, we help innovative brands launch products through creators, premium content, and strategic campaigns.", items: [["Consumer tech","/industries#consumer-tech","/images/smart-bike.jpg","A smart bicycle representing consumer technology"],["Smart home & robotics","/industries#smart-home","/images/smart-home.jpg","Smart-home technology in an everyday setting"],["Software & AI","/industries#software-apps","/images/software.jpg","Laptop representing software and AI products"],["Gaming & mobility","/industries#gaming-mobility","/images/gaming.jpg","Neon-lit gaming environment"]].map(([label,href,url,alt],order) => ({ id: id(`industry-${order}`), label, href, image: { url, alt }, order })) },
    videoShowcase: { eyebrow: "Selected work", title: "Big ideas deserve a moment to move.", description: "Explore the kind of creator-led storytelling that gives a product a place in culture—not just a place in the feed.", cta: { label: "Explore selected work", href: "/projects" }, youtubeUrl: "https://www.youtube-nocookie.com/embed/XXEThcQipPM?si=pnda_fbsWGpELB6_", videoTitle: "Creator-led product storytelling" },
    whyTuMedia: { eyebrow: "Why TU Media", title: "The work gets better when every voice is heard.", description: "We believe great creator marketing is a collaboration, not a transaction. That means supporting brands with a clear point of view, while respecting the craft and audience trust creators have built over time.", media: { url: "/images/7.jpeg", alt: "Creator filming technology content" }, items: ["Clear briefs, clear roles, and a practical campaign plan.","Creator partnerships chosen for relevance—not just reach.","Thoughtful support through the moments that matter most.","Reporting that turns activity into useful next steps."].map((text,order) => ({ id: id(`commitment-${order}`), text, order })) },
    blogPreview: { eyebrow: "From the blog", title: "Useful thinking for the work before the work.", cta: { label: "Read the blog", href: "/blogs" }, featuredCount: 3 },
    faq: { eyebrow: "Questions, answered", title: "A clearer way to get started.", description: "Whether you are exploring a launch or your next creator opportunity, these are the first useful things to know.", items: [["What kinds of brands do you work with?","TU Media is focused on technology-led products, from consumer electronics and smart home to apps and software."],["Can creators apply to work with TU Media?","Yes. Our creator network is a separate journey. Tell us about your work and we will be in touch if there is a relevant fit."],["Do you support global campaigns?","We build creator programmes around the markets, platforms, and audiences that matter to each campaign."]].map(([question,answer],order) => ({ id: id(`faq-${order}`), question, answer, order })) },
    finalCta: { eyebrow: "Start a conversation", title: "Have a product people should know about?", description: "Let's make it easier for them to discover.", primaryCta: { label: "Connect with us", href: "/contact" }, reassurance: "Brand and general business enquiries" },
  };
}
